version: '3'
services:
  unbound:
    container_name: unbound
    image: ryansaunders/cloudflare-dns-docker
    ports:
      - 853:53/udp
    restart: unless-stopped
    networks:
      internaldns:
        ipv4_address: 192.168.2.2

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - TZ=America/New York
      - WEBPASSWORD=${WEBPASSWORD}
      - DNS1=192.168.2.2
      - DNS2=no
      - DNSMASQ_LISTENING=all
      - RATE_LIMIT=0/0
      - QUERY_LOGGING=true
    networks:
      internaldns:
        ipv4_address: 192.168.2.3
      proxy:
    dns:
      - 192.168.1.1
      - 127.0.0.1
    restart: unless-stopped
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './var-log/:/var/log/'
    labels:
      - traefik.http.routers.pihole.rule=Host(`${PIHOLE_HOST}`)
      - traefik.frontend.rule=Host:"${PIHOLE_HOST}"
      - traefik.http.services.pihole.loadbalancer.server.port=80
      - traefik.enable=true
      - traefik.http.routers.pihole.tls=true
      - traefik.http.routers.pihole.tls.certresolver=certificato
      - --accesslog.format=json

networks:
  internaldns:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  proxy:
