version: '3'
services:
  cloudflare-dns-tls:
    image: ryansaunders/cloudflare-dns-docker
    container_name: cloudflare-dns-docker
    ports:
      - 853:53/udp
    restart: always
    logging:
      driver: splunk
      options:
        splunk-token: ${SPLUNK_TOKEN}
        splunk-url: ${SPLUNK_URL}
        splunk-insecureskipverify: "true"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        labels: "unbound-dns"
